### ISSUE TITLE
Using ESP32 PSRAM to create huge RGB Matrix Panel display

### ISSUE THREAD

**Issue by tsctrl** [mrcodetastic/ESP32-HUB75-MatrixPanel-DMA#100]
Hi @mrfaptastic ,

sorry again to ask alot. 

i would like to suggest capability to allocate ram usage to use ps ram on wrover module. seems like adding this is not a big change.

adding flags or variable to switch malloc to ps_malloc should suffice to have the capability and allow more option to run higher bit graphic on the wrover module.

thank you!

**Comment by mrfaptastic** [comment]
ESP32 doesn't support DMA from PSRAM

**Comment by mrfaptastic** [comment]
https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA/issues/55

**Comment by sheepov** [comment]
Hi,

Any issue using this ESP32-HUB75-MatrixPanel-I2S-DMA & PSRAM (wrover) ?
Do you have test the CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL ("Reserve this amount of bytes for data that specifically needs to be in DMA or internal memory") option ? 
=> https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/kconfig.html#config-spiram-malloc-reserve-internal


I need more ram for my project..
thx for your work!

**Comment by mrfaptastic** [comment]
I don't understand what your question is.

**Comment by sheepov** [comment]
is it possible to use this lib & PSRAM?

see README.md, memory constraints => it is not possible 
but  using "CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL" may solve the problem?

test using this lib with PSRAM enable on wrover : 
My program crash when i use this instruction  :
    if( not dma_display->begin(//mini esp prod
        12, //r1, 
        14, //g1, 
        27, //b1,
        22, //r2,
        23, //g2,
        2, //b2
        15, //a
        21, //b,
        16, //c,
        17, //d,
        34, //e,
        18, //lat,
        19, //oe,
        5 //clk
        ))
      Serial.println("****** !KABOOM! Insufficient memory - allocation failed ***********");      

=> no error msg but sometimes a weird character is printed : 13:40:00.630 -> l⸮

**Comment by mrfaptastic** [comment]
ESP32 doesn't support DMA from PSRAM

**Comment by sheepov** [comment]
Hi,

I understand : this is not possible to use this lib from internal RAM and
enable PSRAM.

Le jeu. 15 avr. 2021 à 18:54, mrfaptastic ***@***.***> a
écrit :

**Comment by mrfaptastic** [comment]
PSRAM support is now available on ESP32-S3 only, but output throughput ('clock rate') is limited to 10Mhz due to hardware limitations.

20Mhz is available if you continue to use the limited SRAM - but then you face the same old problem of not being able to have a huge resolution..

In summary: There's not much benefit in using PSRAM as the low througput negates the value of having extra memory/possible chains of panels = flicker.

https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/discussions/343
