### ISSUE TITLE
Is it possible, to send gif animation file through Bluetooth to ESP32 ? 

### ISSUE THREAD

**Issue by davemaster** [mrcodetastic/ESP32-HUB75-MatrixPanel-DMA#444]
Greetings,

Is it possible, to send gif animation file through Bluetooth to ESP32, then save it to SD card, then show it in RGB Panel as usual...

Best regards

**Comment by mzashh** [comment]
Idk about Bluetooth but I did the same with WIFI, by using an ASYNC webserver to send gif files to the spiff and play them.
here it is if you are intrested.

https://github.com/mzashh/HUB75-Pixel-Art-Display

**Comment by davemaster** [comment]
Very kind from You for this advice... I'll check it out. 

But I'm still want to do this  using only Bluetooth, I think WiFi link need a lot of additional functions to be accomplished, or I'm wrong? Thanks again, and thanks for those who give me advice like this

**Comment by mzashh** [comment]
> Very kind from You for this advice... I'll check it out.
> 
> But I'm still want to do this using only Bluetooth, I think WiFi link need a lot of additional functions to be accomplished, or I'm wrong? Thanks again, and thanks for those who give me advice like this

imo WIFI on the ESP32 is more simpler than Bluetooth, as you need a dedicated app or something to send files to the ESP32, WIFI is much simpler, my code above has a simple WEB-UI to upload GIFs which can be accessed via any WIFI capable device on your network. . Why don't you give it a try and see if it suits your needs.

**Comment by davemaster** [comment]
What about the power consumption, is WiFi less or more energy demand than Bluetooth? Thanks in advance.

**Comment by mzashh** [comment]
BLE should have considerably low power consumption than WIFI, on avg I had 200mA going to the ESP32 but considering that you are using a LED matrix I don't think it should be significant, also you can disable the WIFI in code when not in use

**Comment by mrfaptastic** [comment]
Enabling Bluetooth on the ESP32 will also chew a lot of memory that might be of better use. 

If the sketch already uses WiFi it would probably easier and more reliable to to use that + mDNS for discovery.

**Comment by chaines8** [comment]
To go to the LCD OLED TFT screen, how do you do it
