### ISSUE TITLE
DrawIcon with VirtualMatrixPanel (2X2 structure) is not Implemented yet (class VirtualMatrixPanel' has no member named drawIcon)

### ISSUE THREAD

**Issue by Abdulrahman-owayj** [mrcodetastic/ESP32-HUB75-MatrixPanel-DMA#585]
hi, Im using 4 panels with (2x2) structure, it works great with (fillRect, print , etc), but I see that there is no drawicon function implemented yet, when trying to solve it i found your note in the library.

```
/*
// need to recreate this one, as it wouldn't work to just map where it starts.
inline void VirtualMatrixPanel::drawIcon (int *ico, int16_t x, int16_t y, int16_t icon_cols, int16_t icon_rows) {
  int i, j;
  for (i = 0; i < icon_rows; i++) {
    for (j = 0; j < icon_cols; j++) {
      // This is a call to this libraries version of drawPixel
      // which will map each pixel, which is what we want.
      //drawPixelRGB565 (x + j, y + i, ico[i * module_cols + j]);
    drawPixel (x + j, y + i, ico[i * icon_cols + j]);
    }
  }
}
*/
```

I appreciate your effort for this library, You did a very fantastic job!

**Comment by Abdulrahman-owayj** [comment]
Well, i tried your commented code and it works great, im not sure why its not released.

the only problem is that when i use drawIcon more than one time the DRAM is filled and i get an error, i need to find a solution to release resources after every call


thank you for your effort

**Comment by Lukaswnd** [comment]
The VirtualMatrixPanel itselfe is not ment to have any GFX functionallity. You are suppost, to use Adafruit_GFX, GFX, or any other GFX implementation, you have to combine yourselfe.

**Comment by mrcodetastic** [comment]
I will be removing drawIcon from the library at some point.
