### ISSUE TITLE
VirtualMatrixPanel::_virtualResX - Not initialized when using NO_GFX

### ISSUE THREAD

**Issue by netmindz** [mrcodetastic/ESP32-HUB75-MatrixPanel-DMA#594]
`VirtualMatrixPanel::getCoords` expects to use `_virtualResX` and `_virtualResY` to be defined, but these are only defined by `VirtualMatrixPanel::setRotatio`n which is not called by default

You can work around the issue by calling       `fourScanPanel->setRotation(0);`  otherwise, you just get no output

**Comment by mrfaptastic** [comment]
Thank you for picking up on this.  If you have a suggested fix, please feel free to raise a pull request, and I'll merge.
