### ISSUE TITLE
P5 screens in chains, 3.0.9 and 3.0.10 horizontal misalignment

### ISSUE THREAD

**Issue by zvonko32** [mrcodetastic/ESP32-HUB75-MatrixPanel-DMA#609]
When I installed version 3.0.10 I noticed a horizontal shift when the screens are connected in chains (2x2), the same is with version 3.0.9., on 3.0.8 everything displays correctly.
Chip FM6124D

p.s. great library, big thanks to the author.

![ggg](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/122110031/8f1c0ea9-5dba-4879-9993-0208fe64a125)

**Comment by zvonko32** [comment]
Now I see that this problem could be Issue "2: Vertical output isn't aligned", I will test tomorow.

**Comment by mrcodetastic** [comment]
Yeah. I changed the default as having it the other way caused issues with more than 50% of the users of this library.

**Comment by mrcodetastic** [comment]
Please feel free to raise a pull request for where you see this error.
