### ISSUE TITLE
Is there support for FM6124C HUB75E displays?

### ISSUE THREAD

**Issue by TheSouthernFrontier** [mrcodetastic/ESP32-HUB75-MatrixPanel-DMA#644]
I have a HUB75E board that uses a FM6124C chip.
Does this library have support for this chip, or is there an alternative library that can support the FM6124C with ESP32?

**Comment by mrcodetastic** [comment]
This library does not contain code specific to FM6124C, so probably not supported.

**Comment by cris-maillo** [comment]
@TheSouthernFrontier my board has FM6124C chip and I've managed to get it working (although I'm having an issue with some of the pixels being mapped incorrectly but I think it must be one of the pins being in the wrong place)

**Comment by board707** [comment]
There is nothing specific in FM6124 driver, it should be supported by the library without any modification of the current code.
