### ISSUE TITLE
Is there support for 128x64 Panel with ICND1065 chip

### ISSUE THREAD

**Issue by KEBAP5000** [mrcodetastic/ESP32-HUB75-MatrixPanel-DMA#653]
Hello!

Thanks for your great library!
Today i got new panels with 128x64px (HUB75E) and chip ICND1065. The problem is, that the whole display stays black. Is this chip not supported?

![IMG_2339](https://github.com/mrcodetastic/ESP32-HUB75-MatrixPanel-DMA/assets/39532189/0e7d6cec-1bcd-4391-8359-a9c71adb30ac)

Thanks for your answer!

**Comment by board707** [comment]
According to my databse, ICDN1065 is a s-PWM type driver. It means that the panel hardly will works with the library.

**Comment by KEBAP5000** [comment]
Thanks for the quick reply!

Do you happen to know whether it only doesn't work with this library, or whether it generally can't work with the ESP32?

And if it could work with another library, which one would that be? :)

**Comment by board707** [comment]
I don't know the library (for any board), that support this driver

**Comment by KEBAP5000** [comment]
Thanks!

One last question: Do you happen to know which 128x64 (P2.5) Panel (or which chips) would work with the ESP32? And do you know a reseller for those?

**Comment by board707** [comment]
I don't know the specific panels. As for chip models, I have a table of drivers that people have tried to run with this and other libraries. Of course, it is not complete and may be inaccurate, but in principle this data can be useful.
[LED Drivers database](https://github.com/board707/DMD_STM32/wiki/Led_drivers)

**Comment by ibhenkz** [comment]
Hi board707, I have same issue with chip ICND1065 pairing chip 74HC245. There is no response in panel 128x64 (fully black).
are you plan to make a config for enable those chips, because I'am really happy using ESP32-HUB75-MatrixPanel-DMA for many projects. Thanks for Advance.

**Comment by board707** [comment]
> are you plan to make a config for enable those chips, because I'am really happy using ESP32-HUB75-MatrixPanel-DMA for many projects.

Hi
First of all, the ESP32-HUB75-MatrixPanel-DMA is not my project, so you should ask the author - @mrcodetastic.

As for me, I am interesting to develop code for S-PWM drivers, but it is possible only for panels that I have available. 
I don't have panels with the 1065 driver, so I won't be working on them in the near future.

**Comment by ibhenkz** [comment]
> > are you plan to make a config for enable those chips, because I'am really happy using ESP32-HUB75-MatrixPanel-DMA for many projects.
> 
> Hi First of all, the ESP32-HUB75-MatrixPanel-DMA is not my project, so you should ask the author - @mrcodetastic.
> 
> As for me, I am interesting to develop code for S-PWM drivers, but it is possible only for panels that I have available. I don't have panels with the 1065 driver, so I won't be working on them in the near future.

Hi board707,
I am sorry and Thanks for information..
