### ISSUE TITLE
Latest GDMA / LCD changes to S3 not working

### ISSUE THREAD

**Issue by Lukaswnd** [mrcodetastic/ESP32-HUB75-MatrixPanel-DMA#655]
I have some problem with the latest changes.

This changes in esp32s3/gdma_lcd_parallel16.cpp starting at line 272:
>     /*
>     static gdma_tx_event_callbacks_t tx_cbs = {
>        // .on_trans_eof is literally the only gdma tx event type available
>       .on_trans_eof = gdma_on_trans_eof_callback 
>     };
>     gdma_register_tx_event_callbacks(dma_chan, &tx_cbs, NULL);
>     */
> 
>      //
>     // Enable Transaction Done interrupt
>     LCD_CAM.lc_dma_int_ena.lcd_trans_done_int_ena = 1;
> 
>     // Allocate a level 1 intterupt: lowest priority, as ISR isn't urgent and may take a long time to complete
>     esp_intr_alloc(ETS_LCD_CAM_INTR_SOURCE, (int)(ESP_INTR_FLAG_IRAM | ESP_INTR_FLAG_LEVEL1), lcd_isr, NULL, NULL);

the lcd_isr never get's called, thus the previous buffeer will never be free. 
I'm using Arduino a Project (generic esp32s3 + 128x64 1/32 scan matrix) which worked fine till I updated the lib and when I undo the changes in this section everything works fine. The esp_intr_alloc returns ESP_OK. Changing the flags does not work either.
Is there maybe a difference in Arduino and IDF?

when I change the interrupt from lcd_trans_done_int_ena to lcd_vsync_int_ena it gets triggert, but way to often (watchdog triggers) and probably not at the right time. I have tried to clear the interrupt: LCD_CAM.lc_dma_int_clr.lcd_trans_done_int_clr = 1; at differnt times, nothing works.
Maybe the transition is never done, because it is chained infinite?

Differnt topic:
And I have to ask why you changed the clk_speed? some panels are able to achive the 20mhz or even more, why not set the default low, so most people won't complain and still enable higher frequencies?

**Comment by mrcodetastic** [comment]
I've reverted this.

As for clkspeed, it's to fix issues with ESP and ESPS2 which was not right. I've added 20Mhz back in, but I don't have a scope quick enough to confirm that ever worked on the GPIO output on the S3.
