### ISSUE TITLE
nullptr dereference

### ISSUE THREAD

**Issue by DevxMike** [mrcodetastic/ESP32-HUB75-MatrixPanel-DMA#675]
examples/1_SimpleTestShapes/1_SimpleTestShapes.ino

//MatrixPanel_I2S_DMA dma_display;
MatrixPanel_I2S_DMA *dma_display = nullptr;

uint16_t myBLACK = dma_display->color565(0, 0, 0);
uint16_t myWHITE = dma_display->color565(255, 255, 255);
uint16_t myRED = dma_display->color565(255, 0, 0);
uint16_t myGREEN = dma_display->color565(0, 255, 0);
uint16_t myBLUE = dma_display->color565(0, 0, 255);

**Comment by mrcodetastic** [comment]
Can you raise a pull request with the fix please?

**Comment by DevxMike** [comment]
yeah, why not
