### ISSUE TITLE
how to run on esp-idf

### ISSUE THREAD

**Issue by hijoh** [mrcodetastic/ESP32-HUB75-MatrixPanel-DMA#687]
thank you so much ,do you have a sample on esp-idf？

**Comment by abrender** [comment]
Hi @hijoh - there are two example folders in [examples/esp-idf](https://github.com/mrcodetastic/ESP32-HUB75-MatrixPanel-DMA/tree/master/examples/esp-idf) showing how to use this library with `esp-idf` (there is a README.md in each directory).

If you run into any specific problems please let us know and we'll do our best to help you out :)

**Comment by hijoh** [comment]
esp-idf5.1,succsessful,thank you!
<img width="751" alt="Snipaste_2024-10-11_17-25-16" src="https://github.com/user-attachments/assets/fd90f70a-1593-463a-a7bb-76ed6182e4c3">

**Comment by hijoh** [comment]
> Hi @hijoh - there are two example folders in [examples/esp-idf](https://github.com/mrcodetastic/ESP32-HUB75-MatrixPanel-DMA/tree/master/examples/esp-idf) showing how to use this library with `esp-idf` (there is a README.md in each directory).
> 
> 
> 
> If you run into any specific problems please let us know and we'll do our best to help you out :)

I successfully ran in IDF 5.1 and with GFX. But how can I display Chinese?
